### ISSUE TITLE
Sui Mainnet 1.15.1 panic issue

### ISSUE THREAD

**Issue by fanbsb** [shinamicorp/sui-docker#177]
There is a panic issue in version mainnet-v1.15.1, could you help create a new release for the 1.15.2 please?

https://github.com/MystenLabs/sui/releases/tag/mainnet-v1.15.2

**Comment by jasonxh** [comment]
It was built as part of https://github.com/shinamicorp/sui-docker/pull/175, though the images were tagged with `b4687af`, not `mainnet-v1.15.2` (identical git commit). We'll build the next mainnet release as it's officially released on github

**Comment by fanbsb** [comment]
Thanks, the b4687af is working fine for now
